reciclo/src/home/urls.py
from django.conf.urls import url

from .views import HomeView, LoginView, SignupView, LogoutView


urlpatterns = [
    url(
        r'^$',
        HomeView.as_view(),
        name='home',
    ),
    url(
        r'^login/$',
        LoginView.as_view(),
        name='login',
    ),
    url(
        r'^signup/$',
        SignupView.as_view(),
        name='signup',
    ),
    url(
        r'^logout/$',
        LogoutView.as_view(),
        name='logout',
    ),
]

reciclo/src/reciclo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from trashcan.views import TrashCanViewSet, LevelViewSet

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'trash-cans', TrashCanViewSet)
router.register(r'levels', LevelViewSet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # Home.
    url(r'^', include('home.urls', namespace='home_app')),
    # Trashcan.
    url(r'^cans/', include('trashcan.urls', namespace='trashcan_app')),
    # DRF.
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include(router.urls)),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

reciclo/src/trashcan/urls.py
from django.conf.urls import url

from .views import my_list_view, CreateView, DetailView


urlpatterns = [
    url(
        r'^$',
        my_list_view,
        name='can-list',
    ),
    url(
        r'^(?P<pk>[0-9]+)/$',
        DetailView.as_view(),
        name='can-detail',
    ),
    url(
        r'^crear/$',
        CreateView.as_view(),
        name='can-create',
    ),
]

reciclo/src/trashcan/models.py
from django.contrib.auth.models import User
from django.db import models


class TrashCanQuerySet(models.QuerySet):

    def get_not_address(self):
        return self.filter(
            models.Q(address='') | models.Q(address__isnull=True)
        )

    def get_lat_lng(self):
        return self.filter(
            lat__isnull=False,
            lng__isnull=False,
        )

    def get_barcode(self):
        return self.filter(
            ~models.Q(barcode=''),
            barcode__isnull=False,
        )

    def count_barcode(self):
        return self.get_barcode().count()

    def get_gt_depth(self, depth):
        return self.filter(
            depth__gt=depth,
        )


class TrashCan(models.Model):

    depth = models.FloatField(help_text='Profundidad del tacho.')
    barcode = models.CharField(
        max_length=100,
        null=True,
        blank=True,
    )
    lat = models.FloatField(
        null=True,
        blank=True,
    )
    lng = models.FloatField(
        null=True,
        blank=True,
    )
    address = models.CharField(
        max_length=300,
        null=True,
        blank=True,
    )

    recyclers = models.ManyToManyField(
        User,
        through='Harvest',
    )

    objects = TrashCanQuerySet.as_manager()

    def has_address(self):
        return bool(self.address)
        # if self.address:
        #     return True
        # return False

    @property
    def tiene_address(self):
        return self.has_address()

    def set_address(self):
        if self.tiene_address:
            return
        self.address = 'Almacen Pripal'

    def save(self, *args, **kwargs):
        self.set_address()
        super(TrashCan, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.pk)

    class Meta:
        db_table = 'trash_can'


class LevelQuerySet(models.QuerySet):

    def get_levels(self, trash_can_pk):
        return self.filter(trash_can=trash_can_pk).order_by('-time')


class Level(models.Model):

    trash_can = models.ForeignKey(
        TrashCan,
        related_name='levels',
    )
    time = models.DateTimeField(
        auto_now_add=True,
    )
    distance = models.FloatField(
        help_text='Distancia del sensor a la basura (cm).'
    )

    objects = LevelQuerySet.as_manager()

    def __str__(self):
        return str(self.pk)

    class Meta:
        db_table = 'level'


class Harvest(models.Model):

    user = models.ForeignKey(User)
    trash_can = models.ForeignKey(TrashCan)
    date = models.DateField()

    STATUS = (
        (0, 'Por recoger'),
        (1, 'Trabajo hecho'),
    )
    status = models.BooleanField(
        max_length=50,
        choices=STATUS,
        default=0,
    )
    comment = models.TextField(
        blank=True,
        null=True,
    )

    def __str__(self):
        return str(self.pk)

    class Meta:
        db_table = 'harvest'
        unique_together = ('user', 'trash_can', 'date')

reciclo/src/trashcan/forms.py
from django import forms
from django.forms import ModelForm

from .models import TrashCan


class TrashCanForm(ModelForm):

    class Meta:
        model = TrashCan
        exclude = (
            'recyclers',
        )

reciclo/src/trashcan/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View

from rest_framework import viewsets

from .models import TrashCan, Level
from .forms import TrashCanForm
from .serializers import TrashCanSerializer, LevelSerializer


def my_list_view(request):
    template_name = 'trashcan/lista.html'
    context = {
        'cans': TrashCan.objects.get_lat_lng(),
    }
    return render(request, template_name, context)


class CreateView(View):

    template_name = 'trashcan/crear.html'
    form = TrashCanForm

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('home_app:home')
        context = {
            'errors': kwargs.get('errors'),
            'form': self.form,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            data = dict(request.POST)
            data.pop('csrfmiddlewaretoken')
            data = {k: v[0] for k, v in data.items()}
            TrashCan.objects.create(**data)
            return redirect('trashcan_app:can-list')
        return self.get(request, errors=form.errors)


class DetailView(View):

    template_name = 'trashcan/detalle.html'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('home_app:home')
        pk = kwargs.get('pk')
        context = {
            'errors': kwargs.get('errors'),
            'can': TrashCan.objects.filter(pk=pk).first(),
            'levels': Level.objects.get_levels(pk),
        }
        return render(request, self.template_name, context)


class TrashCanViewSet(viewsets.ReadOnlyModelViewSet):

    queryset = TrashCan.objects.all()
    serializer_class = TrashCanSerializer
    filter_fields = (
        'barcode',
    )
    search_fields = (
        'barcode',
    )


class LevelViewSet(viewsets.ModelViewSet):

    queryset = Level.objects.all()
    serializer_class = LevelSerializer

reciclo/src/templates/trashcan/crear.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>Crear Cans</h1>

	{% if errors %}
		{{errors}}
	{% endif %}

	<form action="{% url 'trashcan_app:can-create' %}" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit">
	</form>

	<br>

	<a href="{% url 'trashcan_app:can-list' %}">Volver a listado</a>

</body>
</html>

reciclo/src/templates/trashcan/detalle.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>Listado|Cans</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static "css/home.css" %}">
</head>
<body>
	<h1>Detalle {{ can.pk }}</h1>

	<li>Tamano: {{can.depth}}</li>
	<li>Barcode: {{can.barcode}}</li>
	<li>Direccion: {{can.address}}</li>
	<li>{{can.lat}}</li>
	<li>{{can.lng}}</li>

	<br>
	<br>

	<table style="width:100%">
		<thead>
			<tr>
				<th>id</th>
				<th>tiempo</th>
				<th>distancia al sensor</th>
			</tr>
		</thead>
		<tbody>
			{% for level in levels %}
			<tr>
				<td>{{level.id}}</td>
				<td>{{level.time}}</td>
				<td>{{level.distance}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

	<p>
		<a href="{% url 'trashcan_app:can-list' %}"> Volver al listado</a>
	</p>
</body>
</html>

reciclo/src/templates/trashcan/lista.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <title>Listado|Cans</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "css/home.css" %}">
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDKNA5bEc9XhbROSdRg3tEHwgIuZFJqBDw" type="text/javascript"></script>
</head>
<body>

    <div id="map" style="width:100%; height:400px"></div>

    <h1>Listado</h1>
    {% for can in cans %}
    <ul>
        <a href={% url 'trashcan_app:can-detail' can.pk %}>{{can.pk}}</a>
        <li>Tamano: {{can.depth}}</li>
        <li>Barcode: {{can.barcode}}</li>
        <li>Direccion: {{can.address}}</li>
        <li>{{can.lat}}</li>
        <li>{{can.lng}}</li>
    </ul>
    {% endfor %}

    <p>
        <br>
        {% if user.is_authenticated %}
            <a href="{% url 'trashcan_app:can-create' %}">Crear</a>
            <br>
            <br>
            <a href="{% url 'home_app:logout' %}">Cerrar Sesion</a>
        {% endif %}
        <br>
        <a href={% url 'home_app:home' %}> Volver </a>
    </p>

    <script>
    function initialize() {
        var marcadores = [];
        {% for can in cans %}
            marcadores.push(["{{can.address}}", {{can.lat}}, {{can.lng}}]);
        {% endfor %}
        
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: new google.maps.LatLng(-12.070242, -77.042152),
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });
        
        var infowindow = new google.maps.InfoWindow();
        var marker, i;
        
        for (i = 0; i < marcadores.length; i++) {  
            marker = new google.maps.Marker({
              position: new google.maps.LatLng(marcadores[i][1], marcadores[i][2]),
              map: map
            });
            google.maps.event.addListener(marker, 'click', (function(marker, i) {
              return function() {
                infowindow.setContent(marcadores[i][0]);
                infowindow.open(map, marker);
              }
            })(marker, i));
        }
    }
    google.maps.event.addDomListener(window, 'load', initialize);
    </script>
</body>
</html>