reciclo/src/home/urls.py
from django.conf.urls import url

from .views import HomeView, LoginView, SignupView, LogoutView


urlpatterns = [
    url(
        r'^$',
        HomeView.as_view(),
        name='home',
    ),
    url(
        r'^login/$',
        LoginView.as_view(),
        name='login',
    ),
    url(
        r'^signup/$',
        SignupView.as_view(),
        name='signup',
    ),
    url(
        r'^logout/$',
        LogoutView.as_view(),
        name='logout',
    ),
]

reciclo/src/reciclo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from trashcan.views import TrashCanViewSet, LevelViewSet

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'trash-cans', TrashCanViewSet)
router.register(r'levels', LevelViewSet)


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # Home.
    url(r'^', include('home.urls', namespace='home_app')),
    # Trashcan.
    url(r'^cans/', include('trashcan.urls', namespace='trashcan_app')),
    # DRF.
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include(router.urls)),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

reciclo/src/trashcan/urls.py
from django.conf.urls import url

from .views import my_list_view, CreateView, DetailView


urlpatterns = [
    url(
        r'^$',
        my_list_view,
        name='can-list',
    ),
    url(
        r'^(?P<pk>[0-9]+)/$',
        DetailView.as_view(),
        name='can-detail',
    ),
    url(
        r'^crear/$',
        CreateView.as_view(),
        name='can-create',
    ),
]

reciclo/src/home/models.py
from django.db import models

# Create your models here.

reciclo/src/home/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm


class UserForm(ModelForm):

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if not first_name:
            raise forms.ValidationError(
                'El nombre es requerido.'
            )
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if not last_name:
            raise forms.ValidationError(
                'El apellido es requerido.'
            )
        return last_name

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'password',
        )

reciclo/src/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import TemplateView, View
from django.contrib.auth.models import User

from .forms import UserForm


class HomeView(TemplateView):
    template_name = "home/landing.html"


class LoginView(View):

    template_name = "home/login.html"

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('home_app:home')
        context = {}
        return render(request, self.template_name, context)

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('trashcan_app:can-list')
        return self.get(request)


class SignupView(View):
    
    template_name = "home/signup.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home_app:home')
        context = {
            'errors': kwargs.get('errors'),
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']

            user = User.objects.create(
                username=username,
                first_name=first_name,
                last_name=last_name,
            )
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('trashcan_app:can-list')
        return self.get(request, errors=form.errors)


class LogoutView(View):

    def get(self, request):
        logout(request)
        return redirect('home_app:home')

reciclo/src/templates/home/landing.html
<!DOCTYPE html>
<html>
<head>
	<title>Landing</title>
</head>
<body>
	<h1>Bienvenid@ a Reciclo
	{% if user.is_authenticated %}
		{{user.first_name}}
	{% endif %}
	!
	</h1>

	<p>Tenemos tasho intelingente que ayudan a salvar al planeta</p>

	<a href={% url 'trashcan_app:can-list' %}>Ver nuestros tachos</a>

	<hr>

	{% if not user.is_authenticated %}
		<a href="{% url 'home_app:login' %}">Login</a>
		<br>
		<a href="{% url 'home_app:signup' %}">Registro</a>
	{% else %}
		<a href="{% url 'home_app:logout' %}">Cerrar Sesion</a>
	{% endif %}
</body>
</html>

reciclo/src/templates/home/login.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>Login</h1>

	<form action="{% url 'home_app:login' %}" method="POST">
		{% csrf_token %}
		<input type="text" name="username" placeholder="Nombre de Usuario">
		<input type="password" name="password" placeholder="Clave">
		<input type="submit">
	</form>

	<br>

	<a href="{% url 'home_app:home' %}">Volver</a>

</body>
</html>

reciclo/src/templates/home/signup.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>Registro</h1>

	{% if errors %}
		{{errors}}
	{% endif %}

	<form action="{% url 'home_app:signup' %}" method="POST">
		{% csrf_token %}
		<input type="text" name="username" placeholder="Nombre de Usuario">
		<br>
		<input type="text" name="first_name" placeholder="Nobmres">
		<br>
		<input type="text" name="last_name" placeholder="Apellidos">
		<br>
		<input type="password" name="password" placeholder="Clave">
		<br>
		<input type="submit">
	</form>

	<br>

	<a href="{% url 'home_app:home' %}">Volver</a>

</body>
</html>